version: '3'
services:
  sequeldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-data:/var/lib/mysql/
volumes:
  mysql-data:
    driver: local
